### ISSUE TITLE
Is it possible to override the UploadOptions in a Component?

### ISSUE THREAD

**Issue by jcheros** [wKoza/ngx-upload#10]
I need override the UploadOptions

`const uploadOptions: UploadOptions = {
  method : 'POST',
  url: 'your_backend_upload_url',
  httpStrategy: HttpClientUploadService
};`

`NgxUploadModule.forRoot(uploadOptions, ngxDropTargetOptions)`

Like DropTargetOptions
`[ngxDragAndDrop]="options"`

**Comment by wKoza** [comment]
Hi,
Can you explain me your use case. have you to change your url between different components / services ?

**Comment by jcheros** [comment]
Hi!
Yes, I have several components and the URL to upload files is different in each of them.
What I can do?

Regards.

**Comment by wKoza** [comment]
Currently, It's a little tricky. I'll modify the library this weekend in this sense.

**Comment by wKoza** [comment]
This new version removes UploadOptions from the forRoot and a endpoint have to be declared for each call;
