### ISSUE TITLE
Multiple and Accept inputs on the directive

### ISSUE THREAD

**Issue by bnweiss** [wKoza/ngx-upload#17]
I attempted to figure out how to add something like <input [multiple]="multiple" [accept]="accept"> to the directive so that those options can be set dynamically.  Don't have much experience with component factories though.  Is there a way to accomplish this?  Thanks for the program!

**Comment by wKoza** [comment]
Hi @bnweiss ,
I can add the feature this weekend; It's a good idea;

**Comment by wKoza** [comment]
closes with 6.4.0 - PR #18
