### ISSUE TITLE
If an image is removed and added back - it is not accepting

### ISSUE THREAD

**Issue by ausshadu** [wKoza/ngx-upload#20]
The `(change)="onFilesAdded()"` method is not firing because the input value hasn't changed. The work around is clear the value of input once it is added to the queue.

Known Issue: This will add multiple instances of the same image.

**Comment by wKoza** [comment]
Hi @ausshadu,
I'm going to wait your change in your PR and I'll merge that.
Best regards,

**Comment by wKoza** [comment]
closed by PR #56
