### ISSUE TITLE
In ng-template doesn't accept variable

### ISSUE THREAD

**Issue by ghten** [wKoza/ngx-upload#22]
In ng-template if you put <ng-template ngxInputFile="optionsInput"> upload file </ng-template>, no problem but if you put <ng-template ngxInputFile="optionsInput"> {{ 'button.upload photo'|translate }} </ng-template> you see nothing, no button, no text, the button disappears.

Thanks

**Comment by wKoza** [comment]
Hi,
Thank you for your issue, I'll take a look this weekend.

**Comment by wKoza** [comment]
If I put that : 
```html
<ng-template ngxInputFile="optionsInput"> {{title}}</ng-template>
```

I have no problem. What is your pipe `translate`?

**Comment by wKoza** [comment]
I suppose we can close this issue. You can create a new issue whether your problem persists.
