### ISSUE TITLE
Pull and Publish

### ISSUE THREAD

**Issue by kKen94** [wKoza/ngx-upload#23]
I think there are some interesting improvements on the @banksemi fork and I wanna ask if it is possible integrate it and when you publish an update on npm.
I really need the index.ts update because actually angular doesn't compile the library if I enable Ivy

**Comment by wKoza** [comment]
Hi @kKen94 ,

I have seen that. I'll integrate this fork this weekend and publish a new version. 

@banksemi, would you like create a pull request with your work ?

**Comment by kKen94** [comment]
Thank you so much!

**Comment by banksemi** [comment]
Okay. I will check the code and create pull request !

**Comment by wKoza** [comment]
I have integrated some improvements form the @banksemi fork but I have to work out on others.

I have released a version 8.0.0-beta.2.
I work on the compatibility with ivy but it's more complicated.
