### ISSUE TITLE
Export all class

### ISSUE THREAD

**Issue by kKen94** [wKoza/ngx-upload#62]
To build without error with Ivy, we need you export all the classes.

This is my error 
![image](https://user-images.githubusercontent.com/46461611/62212512-2bf39100-b3a1-11e9-82ec-d0f64782eafa.png)

**Comment by kKen94** [comment]
With angular 8.2.0 update the error disappears

**Comment by wKoza** [comment]
@kKen94 . Yes, Angular 8.1x was bugged with ivy
