### ISSUE TITLE
ERROR in No NgModule metadata found for 'AppModule'.

### ISSUE THREAD

**Issue by kdbusiness90** [wKoza/ngx-upload#63]
Hello William,

I am getting below error after define NgxUploadModule.forRoot() in app.module.ts.
`ERROR in No NgModule metadata found for 'AppModule'.`

**Comment by wKoza** [comment]
Can you tell me your Angular and ngx-upload version and if you use Ivy or not ?

**Comment by wKoza** [comment]
It should be okay with the version 8.0.3. 
I use Angular 8.2 ...

Can you confirm ?

**Comment by kdbusiness90** [comment]
@wKoza,
Angular version: "~7.1.0"
"@wkoza/ngx-upload": "^8.0.1",

**Comment by wKoza** [comment]
Can you try with the version 8.0.3 because the 8.0.1 is not stable ?

Le mer. 7 août 2019 à 17:43, kdbusiness90 <notifications@github.com> a
écrit :

**Comment by wKoza** [comment]
So, ngx-upload v 8.0.x is not compatible with Angular 7 😥. You can use ngx-upload 6.4.0 if you can.

**Comment by wKoza** [comment]
@kdbusiness90 ,

You can read this for more informations : https://github.com/angular/angular/issues/30413

**Comment by wKoza** [comment]
It's Christmas before the hour ! I have make a release 7.0.0 for Angular 7 @kdbusiness90 .
