### ISSUE TITLE
Error on dependency injection

### ISSUE THREAD

**Issue by kKen94** [wKoza/ngx-upload#64]
Hi!

I know, mantain angular8 with and without Ivy is an aweful work.

Now, with Ivy, library works like a charm.

But without Ivy this is the error in DI:

" Can't resolve all parameters for *Component in **path**: (?) "

**Comment by kKen94** [comment]
https://github.com/angular/angular/issues/31990 here there is opposite error. I Don't know if it is an angular or library issue

**Comment by wKoza** [comment]
hmm, I know that the library works fine with Angular 7 and Angular 8 with Ivy. I'll try with Angular 8 ... But Angular 8 has a lot of bugs ...

**Comment by kKen94** [comment]
😂😂😂 I know

**Comment by wKoza** [comment]
It should be okay with the version 8.0.3. There is a example [here](https://github.com/wKoza/ngx-uploader-app/tree/angular8_without_ivy).
I use Angular 8.2 ...

Can you confirm ?

**Comment by kKen94** [comment]
I also use angular 8.2
It is probably an angular error

**Comment by wKoza** [comment]
Are you tested my last release (8.0.3) ? I've no more error with or without ivy.

**Comment by kKen94** [comment]
I do it now and the error is

![image](https://user-images.githubusercontent.com/46461611/62604480-796b8300-b8f8-11e9-967f-b2ae5df678fb.png)

This the declaration:

![image](https://user-images.githubusercontent.com/46461611/62604948-65745100-b8f9-11e9-82d6-d89a4b157375.png)


And this the usage:

![image](https://user-images.githubusercontent.com/46461611/62604694-df580a80-b8f8-11e9-936b-4cd3c036c6ab.png)

![image](https://user-images.githubusercontent.com/46461611/62604885-3d84ed80-b8f9-11e9-953e-51385aeb0ab1.png)

**Comment by wKoza** [comment]
There is a example [here](https://github.com/wKoza/ngx-uploader-app/tree/angular8_without_ivy).
You can also give me a minimal repro.

**Comment by kKen94** [comment]
I saw the repo, i can't found the reason of the error. I'm seeing that you have uploaded a new version, i'll try it

**Comment by wKoza** [comment]
Hi @kKen94 ,
Have you resolved your problem ?

**Comment by wKoza** [comment]
I suppose we can close this issue. You can create a new issue whether your problem persists.

**Comment by kKen94** [comment]
Sorry, I was on vacation.

It is my problem. I don't understand why, but the same code in a new project works, in this project no. 🤷🏻‍♂️

**Comment by kKen94** [comment]
Have you tried with an application that use NgxUpload in a sub route? I explain myself:

I resolve this bug both importing NgxUploadModule.forRoot() in app.module and in my sub module.

**Comment by wKoza** [comment]
Your sub module is lazy loaded ?

**Comment by kKen94** [comment]
Yes

**Comment by wKoza** [comment]
Normally, you have to import `NgxUploadModule.forRoot()` in your AppModule and `NgxUploadModule`in your sub module. I don't have to call `forRoot` in a sub module. It's a convention lirectly linked  to Angular.
You can take a look at [this repo](https://github.com/wKoza/ngx-uploader-app/tree/angular8_with_lazyloading_module).

**Comment by kKen94** [comment]
So why did it work with the old version?

**Comment by wKoza** [comment]
NgxUpload v8 come with some changes (I use providedIn: 'root' now). So you may have a conflict with the providers. (If you use forRoot() in a sub module, yours services will not be singleton and the behavior is not predictive).
Maybe , the new injector Angular is less permissive ...
