### ISSUE TITLE
Token Authorization 

### ISSUE THREAD

**Issue by evilkent911** [wKoza/ngx-upload#68]
Hi @wKoza , may i know how to include token authorization in the upload service ?

**Comment by wKoza** [comment]
Hi @evilkent911,

If you're talking about bear token witch have to be in your headers, you can add your header like this 

```
uploader.uploadAll({method: 'POST', url: 'my_url'}, **{headers: ...}**).
```

The  same concept  has been used for building `FileItem` :

```
upload(endpoint: UploadEndPoint, options?: any)
```

`Options` is the Angular's object: 

```
options: { headers?: HttpHeaders | { [header: string]: string | string[]; }; observe?: "body"; params?: HttpParams | { [param: string]: string | string[]; }; reportProgress?: boolean; responseType: "arraybuffer"; withCredentials?: boolean; }
```

**Comment by evilkent911** [comment]
hi @wKoza ,
it work. thank you
