### ISSUE TITLE
Not working while drag and drop of .avi file and same is working while upload by file explorer

### ISSUE THREAD

**Issue by manohar719** [wKoza/ngx-upload#69]
Hi, 
I have a implemented the drag and drop functionality for all types of files.
When I am drag and upload the .avi file is it getting $error and for same file if I upload by file explorer and upload it then it works.

I have added all the MIME types
// Videos
	MineTypeEnum.Video,
	MineTypeEnum.Video_Threegpp,
	MineTypeEnum.Video_H264,
	MineTypeEnum.Video_Mp4,
	MineTypeEnum.Video_Mpeg,
	MineTypeEnum.Video_Ogg,
	MineTypeEnum.Video_Quicktime,
	MineTypeEnum.Video_Webm,
	<any>'video/x-msvideo',
	<any>'video/mp2t',
	<any>'video/3gpp2',

**Comment by wKoza** [comment]
fixes with 8.0.6
