### ISSUE TITLE
Mine types

### ISSUE THREAD

**Issue by ghten** [wKoza/ngx-upload#73]
Hi,

I have this in options
public optionsInput: InputFileOptions = {
    multiple: true,
    accept: [MineTypeEnum.Image, MineTypeEnum.Application_Pdf],
  };
but the upload file accept all types of files. I just want images and PDFs

Thanks

**Comment by wKoza** [comment]
Hi @ghten ,
It's curious , I can't reproduce this. 
Which browser do you use ? And what kind of file is problematic ?
If you take a look this link https://ngx-upload.github.io , there is the same configuration.

**Comment by ghten** [comment]
Yes, it's the same configuration, I use firefox but it's the same en chrome. In your example, it's ok in Bootstrap but in material, you have this
![screenshot-ngx-upload github io-2019 12 10-11_55_48](https://user-images.githubusercontent.com/45689669/70523918-579f3880-1b44-11ea-825c-bd0d2f29e046.png)

**Comment by wKoza** [comment]
hmm, it's weird. I can't reproduce that with firefox on MacOS and Windows. 
You dont't have any errors on your console ?

**Comment by ghten** [comment]
It's your example in github, it's your page. There are no errors in the console. 

![screenshot-ngx-upload github io-2019 12 10-13_20_59](https://user-images.githubusercontent.com/45689669/70529251-61c73400-1b50-11ea-951d-20314ffa3034.png)

**Comment by wKoza** [comment]
Ok, I get it when I force to "All file" my explorer / finder.
I'll work out on that.
Thanks for your report.

**Comment by wKoza** [comment]
fixes with commit https://github.com/wKoza/ngx-upload/commit/befeee3e560f810a7f939e90b6c9784fda2f2af3

**Comment by ghten** [comment]
Hi,

Sorry but I downloaded the version and the problem is the same and in your example too.
![FireShot Capture 034 - NgxUploaderIvy - ngx-upload github io](https://user-images.githubusercontent.com/45689669/70860524-05369100-1f23-11ea-9815-8742ac93990f.png)

Have you found a solution? 
And another question it will be possible to select excel files because I have not seen it in the current version

Thanks

**Comment by wKoza** [comment]
Hi,

I uploaded the wrong version thursday. Now, It's the good version (8.0.6). You can try again here https://ngx-upload.github.io/.

Currently, we don't have a specific mimetype for Excel file. It's should be good with `Application` mimeType but it's the especially for Excel .

**Comment by ghten** [comment]
Sorry, this image has been made now.

**Comment by ghten** [comment]
The version in the image is 8.0.6
![FireShot Capture 035 - NgxUploaderIvy - ngx-upload github io](https://user-images.githubusercontent.com/45689669/70861371-4895fd00-1f2d-11ea-9ecb-e6f97014e3fa.png)

**Comment by wKoza** [comment]
Ok , I got it ! I always use the click event on the drag & drop zone. I don't use the button. I can reproduce your issue. 
I'll take a look quickly at this problem

**Comment by wKoza** [comment]
There is a typo in my example. The optionInput wasn't binded . There is the right code :
```html
 <button mat-raised-button [color]="'primary'" >
                        <ng-template [ngxInputFile]="optionsInput"> {{title}}</ng-template>
</button>
```

I change docs / app right now.

**Comment by ghten** [comment]
Ok, it's all right thanks
