### ISSUE TITLE
Mime type

### ISSUE THREAD

**Issue by ghten** [wKoza/ngx-upload#74]
Hi,

It is possible in ngx-upload to accept all types of files.

Thanks

**Comment by wKoza** [comment]
Hi,
Normally, if you don't specify the `accept` option,  ngx-upload doesn't have to fllter your files; Otherwise, you can add the value value '*' like this:

````
optionsInput: InputFileOptions = {
  multiple: true,
  accept: ['*']
};
```

**Comment by ghten** [comment]
Hi,

I have this error

Type '"*"' is not assignable to type 'MineTypeEnum'.

Thanks

**Comment by wKoza** [comment]
Indeed, I've just released a new version with this MineType.
